export const mockIslands = [
    {
        id: '1',
        title: 'fklll;l;;',
        type: 'sort',
        x: 14,
        y: 25,
        progress: 46,
        isLocked: false,
        isCompleted: false,
        order: 2,
    },
    {
        id: '2',
        title: 'f',
        type: 'recursive',
        x: 30,
        y: 50,
        progress: 100,
        isLocked: false,
        isCompleted: true,
        order: 1,
    },
    {
        id: '3',
        title: 'Остров сотировок',
        type: 'plain',
        x: 64,
        y: 25,
        progress: 0,
        isLocked: true,
        isCompleted: false,
        order: 3,
    },
];

export const mockModules = [
    {
        id: '1',
        islandId: '1',
        title: 'fklll',
        order: 1,
        description: 'fklll',
        difficulty: 'EASY',
    },
    {
        id: '2',
        islandId: '2',
        title: 'fklll',
        order: 1,
        description: 'fklll',
        difficulty: 'EASY',
    },
    {
        id: '3',
        islandId: '3',
        title: 'fklll',
        order: 1,
        description: 'fklll',
        difficulty: 'EASY',
    },
    {
        id: '4',
        islandId: '1',
        title: 'fklll',
        order: 1,
        description: 'fklll',
        difficulty: 'EASY',
    },
    {
        id: '5',
        islandId: '2',
        title: 'fklll',
        order: 1,
        description: 'fklll',
        difficulty: 'EASY',
    },
    {
        id: '6',
        islandId: '3',
        title: 'fklll',
        order: 1,
        description: 'fklll',
        difficulty: 'EASY',
    },
    {
        id: '7',
        islandId: '1',
        title: 'fklll',
        order: 3,
        description: 'fklll',
        difficulty: 'EASY',
    },
];
